version: 2.1

jobs:
  verify:
    docker:
      - image: cimg/go:1.26.4
    steps:
      - checkout
      - run:
          name: Install Python virtual environment support
          command: sudo apt-get update && sudo apt-get install -y python3-venv
      - run:
          name: ./godelw verify
          command: ./godelw verify --apply=false

workflows:
  verify:
    jobs:
      - verify
